name = "gpsc-v2"
compatibility_date = "2024-09-01"

# â›” DO NOT set main here (worker.js is default)

# ðŸ”‘ KV STORAGE
[[kv_namespaces]]
binding = "KV"
id = "1a154163dd614f8da7d889b5aa04701b"

# ðŸ—„ D1 DATABASE
[[d1_databases]]
binding = "DB"
database_name = "gpsc-dental-db"
database_id = "5d374e7d-2d0f-4c7e-87ae-aa2e2f949515"

[vars]
ENV = "production"
